server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tsdrs
    username: root
    password: 1234
  data:
    redis:
      database: 0
      port: 6379
      host: localhost
      password: 1234 
  servlet:
    multipart:
      max-file-size: 2MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true